---
- name: Install Torrust
  hosts: torrust
  become: no

  tasks:
    - name: Install some pre-requisites
      community.general.homebrew:
        name:
          - git
          - curl
          - tmux
          - pkg-config
          - openssl
          - sqlite3

    # shoutout to https://dentrassi.de/2020/06/17/headless-installation-of-cargo-and-rust/ for the silent install method
    - name: Install Rust
      shell:
        cmd: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        creates: ~/.cargo/bin/rustc

    - name: Create Torrust folder in /opt/
      file:
        path: /opt/torrust/
        state: directory

    # Torrust Tracker
    - name: Check out torrust-tracker
      git:
        repo: https://github.com/torrust/torrust-tracker.git
        dest: /opt/torrust/torrust-tracker

    - name: Build torrust-tracker
      shell:
        cmd: . "$HOME/.cargo/env" && cargo build --release
        chdir: /opt/torrust/torrust-tracker
        creates: /opt/torrust/torrust-tracker/target/release/torrust-tracker

    - name: Run torrust-tracker once to generate configs
      shell:
        cmd: ./target/release/torrust-tracker
        chdir: /opt/torrust/torrust-tracker
        creates: /opt/torrust/torrust-tracker/config.toml
      ignore_errors: yes

    - name: Configure torrust-tracker
      lineinfile:
        path: /opt/torrust/torrust-tracker/config.toml
        regexp: 'admin = "MyAccessToken"'
        line: 'token = "{{ http_api_access_token }}"'

    # Torrust Index
    - name: Install packages needed for torrust-index
      community.general.homebrew:
        name:
          - node@16
          - nginx

    - name: Add node.js to path
      lineinfile:
        path: ~/.zshrc
        line: 'export PATH="/opt/homebrew/opt/node@16/bin:$PATH"'

    - name: Check out torrust
      git:
        repo: https://github.com/torrust/torrust.git
        dest: /opt/torrust/torrust

    - name: Configure database backend
      copy:
        dest: "/opt/torrust/torrust/backend/.env"
        content: "DATABASE_URL=sqlite://data.db?mode=rwc"

    - name: Install sqlx-cli
      shell:
        cmd: . "$HOME/.cargo/env" && cargo install sqlx-cli
        creates: /root/.cargo/bin/sqlx

    - name: Initialise database
      shell:
        cmd: . "$HOME/.cargo/env" && sqlx db setup
        chdir: /opt/torrust/torrust/backend
        creates: /opt/torrust/torrust/backend/data.db

    - name: Build torrust backend
      shell:
        cmd: . "$HOME/.cargo/env" && cargo build --release
        chdir: /opt/torrust/torrust/backend
        creates: /opt/torrust/torrust/backend/target/release/torrust

    - name: Run torrust backend once to generate configs
      shell:
        cmd: ./target/release/torrust
        chdir: /opt/torrust/torrust/backend
        creates: /opt/torrust/torrust/backend/config.toml
      ignore_errors: yes

    - name: Configure UDP tracker URL
      lineinfile:
        path: /opt/torrust/torrust/backend/config.toml
        regexp: 'url = "udp://localhost:6969"'
        line: 'url = "udp://{{ tracker_url }}:6969"'

    - name: Configure tracker API token
      lineinfile:
        path: /opt/torrust/torrust/backend/config.toml
        regexp: 'token = "MyAccessToken"'
        line: 'token = "{{ http_api_access_token }}"'

    - name: Configure secret key
      lineinfile:
        path: /opt/torrust/torrust/backend/config.toml
        regexp: '^secret_key = '
        line: 'secret_key = "{{ secret_key }}"'

    # Torrust frontend
    - name: Configure torrust frontend
      copy:
        dest: "/opt/torrust/torrust/frontend/.env"
        content: "VITE_API_BASE_URL=http://{{ your_domain }}/api"

    - name: Install npm dependencies
      shell:
        cmd: export PATH="/opt/homebrew/opt/node@16/bin:$PATH" && npm i
        chdir: /opt/torrust/torrust/frontend/
        creates: /opt/torrust/torrust/frontend/dist/index.html

    - name: Run npm build
      shell:
        cmd: export PATH="/opt/homebrew/opt/node@16/bin:$PATH" && npm run build
        chdir: /opt/torrust/torrust/frontend/
        creates: /opt/torrust/torrust/frontend/dist/index.html

    # Configure nginx
    - name: Copy nginx configuration file
      template:
        src: torrust.conf.j2
        dest: /opt/homebrew/etc/nginx/servers/torrust.conf

    - name: Success!
      debug:
        msg:
          - "If you're reading this, Torrust has been successfully deployed to site {{ your_domain }}."
          - "Let us know if it worked, and feel free to reach out if you need help. Enjoy!"
